package com.example.gymgenix;

import java.util.ArrayList;

public class ExerciceListUtils {
    public static final ArrayList<Exercice> exerciceList = new ArrayList<Exercice>() {
        {
            //copy string add(new Exercice("",new String[]{""},""));
            add(new Exercice("Biceps Curl", new String[]{"Biceps"}, "Haut","https://www.google.fr/search?q=biceps+curl&hl=fr&authuser=0&tbm=isch&source=hp&biw=1366&bih=663&ei=3bCTY9xV0YaR1Q_YqoqwDg&iflsig=AJiK0e8AAAAAY5O-7SfLk22USGDwP5CNbdx_josmgDJZ&oq=biceps+c&gs_lcp=CgNpbWcQAxgAMggIABCABBCxAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoICAAQsQMQgwFQAFjyEmCOHmgAcAB4AIABbYgBsQOSAQM3LjGYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img#imgrc=_1Zh26996DfYxM"));
            add(new Exercice("Bench Press", new String[]{"Pectoraux", "Epaule", "Triceps"}, "Haut","https://www.google.fr/search?q=developper+coucher&tbm=isch&ved=2ahUKEwjPhZSxxe37AhUIYRoKHVWoDi0Q2-cCegQIABAA&oq=deve&gs_lcp=CgNpbWcQARgAMgQIABBDMgQIABBDMgQIABBDMgUIABCABDIECAAQQzIICAAQgAQQsQMyBAgAEEMyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAELEDEENQwSJY7ilgyEVoAHAAeACAAYICiAH0A5IBBTQuMC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=6LCTY8_xE4jCadXQuugC&authuser=0&bih=663&biw=1366&hl=fr#imgrc=yjrvGnOQmmjN2M"));
            add(new Exercice("Pull Down", new String[]{"Dos"}, "Haut","https://www.google.fr/search?q=tirage+vertical&tbm=isch&ved=2ahUKEwjbovPxxe37AhUHYxoKHbN8CjQQ2-cCegQIABAA&oq=tirag&gs_lcp=CgNpbWcQARgAMgcIABCxAxBDMgcIABCxAxBDMgQIABBDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoICAAQgAQQsQNQkgtYgxFgiR5oAHAAeACAAU-IAeoCkgEBNpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=cLGTY9uqBofGabP5qaAD&authuser=0&bih=663&biw=1366&hl=fr#imgrc=qCtkJStgk7N13M"));
            add(new Exercice("Squat", new String[]{"Quadriceps", "Ischio-Jambier"}, "Jambes","https://www.google.com/search?q=squat&tbm=isch&tbs=rimg:CacyJ9MojCA4YZPFhvbq9L3ysgIMCgIIABAAOgQIARAA&rlz=1C1CHBF_frFR864FR864&hl=fr&sa=X&ved=0CBwQuIIBahcKEwjQisGpxu37AhUAAAAAHQAAAAAQBg&biw=1349&bih=663#imgrc=03XaygfNDOcDlM"));
            add(new Exercice("Shoulder Press", new String[]{"Epaule", "Triceps"}, "Haut","https://www.google.com/search?q=developper+militaire&tbm=isch&ved=2ahUKEwillt6txu37AhUQaRoKHcEZB6IQ2-cCegQIABAA&oq=deve&gs_lcp=CgNpbWcQARgDMgQIABBDMgUIABCABDIICAAQgAQQsQMyBAgAEEMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAELEDEENQ0xJY9RZgpThoAHAAeACAAUqIAf8BkgEBNZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=7bGTY-XrI5DSacGznJAK&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=EFBOB2zoGaIqHM"));
            add(new Exercice("Hammer Curl", new String[]{"Biceps"},"Haut","https://www.google.com/search?q=hammer+curl&tbm=isch&ved=2ahUKEwjrle7uxu37AhVPwIUKHSHJClcQ2-cCegQIABAA&oq=hammer+&gs_lcp=CgNpbWcQARgAMggIABCABBCxAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoECAAQQzoJCAAQgAQQChAYOgcIABCxAxBDUMQNWP0hYOk2aABwAHgAgAH5AYgBzgSSAQU3LjAuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=drKTY-uCCs-AlwShkqu4BQ&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=vCCvm1rUNTN9XM"));
            add(new Exercice("Back Extension", new String[]{"Dos"}, "Haut","https://www.google.com/search?q=back+extension&tbm=isch&ved=2ahUKEwieoe3pyO37AhULphoKHX3fBqAQ2-cCegQIABAA&oq=bac&gs_lcp=CgNpbWcQARgAMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgcIABCxAxBDMggIABCABBCxAzIECAAQQzIECAAQQzoFCAAQgARQ2RxY-x9gzy9oAHAAeACAAY0CiAG3A5IBBTMuMC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=hLSTY57PIIvMav2-m4AK&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=5OidgnxmH54bkM"));
            add(new Exercice("Side Raise",new String[]{"Epaule"},"Haut","https://www.google.com/search?q=side%20raise&tbm=isch&hl=fr&tbs=rimg:CTca7g4BWOMCYZ73g824lLSLsgIMCgIIABAAOgQIARAA&rlz=1C1CHBF_frFR864FR864&sa=X&ved=0CBsQuIIBahcKEwjwzvvLyu37AhUAAAAAHQAAAAAQBg&biw=1349&bih=663#imgrc=oIYdEWjTGrPO9M"));
            add(new Exercice("Lat Pull Down", new String[]{"Dos"},"Haut","https://www.google.com/search?q=lat%20pulldown&tbm=isch&hl=fr&tbs=rimg:CTXxGaVPdq81YWVjy5N5UGR3sgIOCgIIABAAKAE6BAgBEAE&rlz=1C1CHBF_frFR864FR864&sa=X&ved=0CBoQuIIBahcKEwjglqqU0u37AhUAAAAAHQAAAAAQNA&biw=1349&bih=663#imgrc=xf8V6LXTp4fDQM"));
            add(new Exercice("Seated Cable Row", new String[]{"Dos"},"Haut","https://www.google.com/search?q=horizontal%20row&tbm=isch&hl=fr&tbs=rimg:CW1IIDYuFqKRYd9owWZgOcstsgIOCgIIABAAOgQIARAAQAE&rlz=1C1CHBF_frFR864FR864&sa=X&ved=0CBsQuIIBahcKEwjY7cDP0-37AhUAAAAAHQAAAAAQBg&biw=1349&bih=663#imgrc=fvbJcC7DePngvM"));
            add(new Exercice("Dips", new String[]{"Pectoraux", "Epaule"},"Haut","https://www.google.com/search?q=dips&tbm=isch&ved=2ahUKEwi4oOfV0-37AhVQ0oUKHUHpDVgQ2-cCegQIABAA&oq=dips&gs_lcp=CgNpbWcQAzIHCAAQsQMQQzIECAAQQzIECAAQQzIECAAQQzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoGCAAQBxAeOgQIABAeOggIABCABBCxA1CiC1jwEmDEHmgAcAB4AIABnAGIAZIDkgEDNC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=47-TY_iiEdCklwTB0rfABQ&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=gMYYVJX4OLo00M"));
            add(new Exercice("Pull Up", new String[]{"Dos","Biceps"},"Haut","https://www.google.com/search?q=pull%20ups&tbm=isch&hl=fr&tbs=rimg:CUQeEJoTTFtFYUXuzHYxv1yxsgIOCgIIABAAKAE6BAgBEAE&rlz=1C1CHBF_frFR864FR864&sa=X&ved=0CBwQuIIBahcKEwiIuNm61O37AhUAAAAAHQAAAAAQBw&biw=1349&bih=663#imgrc=ZYT7Cq1kNqoEQM"));
            add(new Exercice("Incline Bench Press", new String[]{"Pectoraux", "Triceps"},"Haut","https://www.google.com/search?q=bench+press+incline&tbm=isch&ved=2ahUKEwjJuuyx1e37AhVJsCcCHZdxBpIQ2-cCegQIABAA&oq=bench+press+incline&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgYIABAFEB4yBggAEAUQHjoECAAQQzoGCAAQBxAeOgYIABAIEB5Q-wtYjBVgvRtoAHAAeACAAckBiAGvBZIBBTcuMC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=sMGTY8miLcngnsEPl-OZkAk&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=6hCX4Jp-vXtb9M"));
            add(new Exercice("Decline Bench Press", new String[]{"Pectoraux", "Triceps"},"Haut","https://www.google.com/search?q=bench+press+decline&tbm=isch&ved=2ahUKEwimo8rC1O37AhUFtBoKHdqHADIQ2-cCegQIABAA&oq=bench+press+decl&gs_lcp=CgNpbWcQARgAMgUIABCABDIECAAQHjIECAAQHjIGCAAQBRAeMgYIABAFEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeOgQIABBDOggIABCABBCxAzoHCAAQsQMQQ1DMGViWSGC9U2gAcAB4AIABWYgB9AeSAQIxN5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=x8CTY-ajGIXoatqPgpAD&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=9-GR0D8TrQv1KM"));
            add(new Exercice("Leg curl", new String[]{"Ischio-Jambier"},"Jambes","https://www.google.com/search?q=leg+curl&tbm=isch&ved=2ahUKEwjbreHY1e37AhXZVaQEHTAyAskQ2-cCegQIABAA&oq=leg+&gs_lcp=CgNpbWcQARgCMgcIABCxAxBDMgcIABCxAxBDMggIABCABBCxAzIECAAQQzIECAAQQzIECAAQQzIFCAAQgAQyBAgAEEMyBQgAEIAEMgQIABBDOgYIABAHEB46BAgAEB5Q4A5Y-hVgxDBoAHAAeACAAViIAbICkgEBNZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=AsKTY9ukFdmrkdUPsOSIyAw&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=_4SdXclFnLs2JM"));
            add(new Exercice("Calf Raises", new String[]{"Mollets"},"Jambes","https://www.google.com/search?q=calf+raises&tbm=isch&ved=2ahUKEwjX_sj_2-37AhXUgHMKHWjZCUYQ2-cCegQIABAA&oq=cal&gs_lcp=CgNpbWcQARgAMgQIABBDMggIABCABBCxAzIECAAQQzIECAAQQzIECAAQQzIICAAQsQMQgwEyBQgAEIAEMggIABCABBCxAzIFCAAQgAQyBAgAEEM6BwgAELEDEENQlApYtw5gyx1oAHAAeACAATqIAdMBkgEBNJgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=nsiTY9e3FdSBzgPosqewBA&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=Yc9Ud9bEf2udFM"));
            add(new Exercice("Bulgarian Split Squat", new String[]{"Quadriceps"},"Jambes","https://www.google.com/search?q=bulgarian+split+squat&tbm=isch&ved=2ahUKEwjJvYa23O37AhUwhM4BHUGUDpUQ2-cCegQIABAA&oq=b&gs_lcp=CgNpbWcQARgAMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDOgYIABAHEB46CAgAEIAEELEDUM0MWK8cYLMuaAFwAHgAgAE7iAGkAZIBATOYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=EMmTY8n1JLCIur4Pwai6qAk&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=LLGzYzI0yQdl4M"));
            add(new Exercice("Leg Extension", new String[]{"Quadriceps"},"Jambes","https://www.google.com/search?q=leg+extension&tbm=isch&ved=2ahUKEwiG6fDL3O37AhUChXMKHUy3DHYQ2-cCegQIABAA&oq=le&gs_lcp=CgNpbWcQARgAMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDOgcIABCxAxBDOgUIABCABDoGCAAQBxAeUOASWOcTYNUbaABwAHgAgAE_iAG4AZIBATOYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=PsmTY4bSF4KKzgPM7rKwBw&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=Y1sWFxiv_emRCM"));
            add(new Exercice("Leg Press", new String[]{"Quadriceps","Ischio-Jambier"}, "Jambes","https://www.google.com/search?q=leg+press&tbm=isch&ved=2ahUKEwiOv6GO3e37AhUHBRoKHeJIBHAQ2-cCegQIABAA&oq=leg+pr&gs_lcp=CgNpbWcQARgAMgcIABCxAxBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgARQyQ1YpQ5gqhZoAHAAeACAATeIAZ0BkgEBM5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=ycmTY862JIeKaOKRkYAH&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=vpr8SK6uCA7lcM"));
            add(new Exercice("Hip Thrust", new String[]{"Fessier"},"Jambes","https://www.google.com/search?q=hip+thrust&tbm=isch&ved=2ahUKEwiJ0pus3e37AhUFtBoKHZ6xCqIQ2-cCegQIABAA&oq=hip&gs_lcp=CgNpbWcQARgAMgcIABCxAxBDMgQIABBDMggIABCABBCxAzIICAAQgAQQsQMyBAgAEEMyCAgAEIAEELEDMggIABCABBCxAzIKCAAQsQMQgwEQQzIFCAAQgAQyBAgAEENQ1_IBWJ72AWCEgAJoAHAAeACAAY8BiAH3ApIBAzQuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=CMqTY4muGYXoap7jqpAK&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=R_wM6p4V4NI00M"));
            add(new Exercice("Triceps Extension", new String[]{"Triceps"},"Haut","https://www.google.com/search?q=tricep+extension&tbm=isch&ved=2ahUKEwjpuuDg3e37AhUBBRoKHexFB44Q2-cCegQIABAA&oq=tri&gs_lcp=CgNpbWcQARgBMgcIABCxAxBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMggIABCABBCxAzIICAAQgAQQsQMyCAgAEIAEELEDOgUIABCABDoLCAAQgAQQsQMQgwE6CAgAELEDEIMBUMAJWI4OYKgeaABwAHgAgAFdiAGNApIBATSYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=dsqTY-mnJIGKaOyLnfAI&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=DiT2TyMRup5g5M"));
            add(new Exercice("Triceps Push Down", new String[]{"Triceps"}, "Haut", "https://www.google.com/search?q=tricep+pushdown&tbm=isch&ved=2ahUKEwj6iPnw3e37AhUNhM4BHSBDAF0Q2-cCegQIABAA&oq=tricep+&gs_lcp=CgNpbWcQARgDMgQIABBDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIECAAQQzIFCAAQgAQ6BggAEAcQHlCqAliqAmDDGWgAcAB4AIABWIgBkwGSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=mMqTY_rcIY2Iur4PoIaB6AU&bih=663&biw=1349&rlz=1C1CHBF_frFR864FR864&hl=fr#imgrc=hWnvZBtvjZL98M"));
        }
    };

    public static ArrayList<Exercice> getExerciceList() {
        return exerciceList;
    }
}
